#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v2
# autospec commit: e661f3a
#
Name     : R-snowfall
Version  : 1.84.6.3
Release  : 50
URL      : https://cran.r-project.org/src/contrib/snowfall_1.84-6.3.tar.gz
Source0  : https://cran.r-project.org/src/contrib/snowfall_1.84-6.3.tar.gz
Summary  : Easier Cluster Computing (Based on 'snow')
Group    : Development/Tools
License  : GPL-2.0
Requires: R-snow
BuildRequires : R-snow
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
parallel R programs. This package offers e.g. extended error
        checks, and additional functions. All functions work in
        sequential mode, too, if no cluster is present or wished.
        Package is also designed as connector to the cluster management
        tool sfCluster, but can also used without it.

%prep
%setup -q -n snowfall
pushd ..
cp -a snowfall buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1701117702

%install
export SOURCE_DATE_EPOCH=1701117702
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/snowfall/DESCRIPTION
/usr/lib64/R/library/snowfall/INDEX
/usr/lib64/R/library/snowfall/Meta/Rd.rds
/usr/lib64/R/library/snowfall/Meta/data.rds
/usr/lib64/R/library/snowfall/Meta/features.rds
/usr/lib64/R/library/snowfall/Meta/hsearch.rds
/usr/lib64/R/library/snowfall/Meta/links.rds
/usr/lib64/R/library/snowfall/Meta/nsInfo.rds
/usr/lib64/R/library/snowfall/Meta/package.rds
/usr/lib64/R/library/snowfall/Meta/vignette.rds
/usr/lib64/R/library/snowfall/NAMESPACE
/usr/lib64/R/library/snowfall/NEWS
/usr/lib64/R/library/snowfall/R/snowfall
/usr/lib64/R/library/snowfall/R/snowfall.rdb
/usr/lib64/R/library/snowfall/R/snowfall.rdx
/usr/lib64/R/library/snowfall/R/sysdata.rdb
/usr/lib64/R/library/snowfall/R/sysdata.rdx
/usr/lib64/R/library/snowfall/data/Rdata.rdb
/usr/lib64/R/library/snowfall/data/Rdata.rds
/usr/lib64/R/library/snowfall/data/Rdata.rdx
/usr/lib64/R/library/snowfall/doc/index.html
/usr/lib64/R/library/snowfall/doc/snowfall.Snw
/usr/lib64/R/library/snowfall/doc/snowfall.pdf
/usr/lib64/R/library/snowfall/help/AnIndex
/usr/lib64/R/library/snowfall/help/aliases.rds
/usr/lib64/R/library/snowfall/help/paths.rds
/usr/lib64/R/library/snowfall/help/snowfall.rdb
/usr/lib64/R/library/snowfall/help/snowfall.rdx
/usr/lib64/R/library/snowfall/html/00Index.html
/usr/lib64/R/library/snowfall/html/R.css
